# Numpy
The NumPy library is the core library for scientific computing in Python. It provides a high-performance multidimensional array
object, and tools for working with these arrays.

In [ ]:
pip install numpy

In [ ]:
import numpy as np

## Creatig Array

In [ ]:
a = np.array([1,2,3])
print(a)

In [ ]:
b = np.array([(1,2,3), (4,5,6), (7,8,9)])
print(b)


In [ ]:
c = np.array([(1,2,3), (4,5,6), (7,8,9)], dtype = float)
print(b)

## Initial place holder

**creating an array is zeror**

In [ ]:
ab = np.zeros((2,3))   
print(ab)


**creating an array is one**

In [ ]:
bb = np.ones((2,5), dtype = str)
print(bb)

**creating an array arrange**

In [ ]:
ag = np.arange(10,35,8) # 10 is the first value and 35 last value arrange b/t 8 distance
print(ag)

In [ ]:
d = np.arange(10,25,5)   # Create an array of evenly spaced values (step value) 
print(d)

 **Create an array of evenly spaced values (number of samples)**

In [ ]:
sv = np.linspace(0,2,9)
print(sv)

**creating constant array**

In [ ]:
c_array = np.full((2,3),7)
print(c_array)

**Create a 2X2 identity matrix**

In [ ]:
f = np.eye(2)
print(f)

In [ ]:
f_9 = np.eye(9)
print(f_9)

**Create an array with random values**

In [68]:
r = np.random.random((4,6))
print(r)

[[0.20514698 0.79523755 0.65146241 0.93294646 0.85073539 0.70566277]
 [0.36433821 0.15677567 0.67017543 0.56515419 0.1102559  0.46630492]
 [0.133555   0.25142005 0.42171043 0.77155622 0.23792664 0.37561736]
 [0.55324692 0.63566668 0.88220656 0.39347387 0.26158539 0.06170241]]


**Create an empty array**

In [75]:
em = np.empty((3,6))
print(em)

[[4.67296746e-307 1.69121096e-306 6.23054293e-307 8.45593934e-307
  7.56593017e-307 1.33511018e-306]
 [1.33511969e-306 1.16819094e-307 8.01097889e-307 1.78020169e-306
  7.56601165e-307 1.02359984e-306]
 [1.33510679e-306 2.22522597e-306 1.11260144e-306 6.89812281e-307
  2.22522596e-306 6.89805151e-307]]


## Data Types